Created desktop version of page "Homes"
ogusti/airbnb-demo-frontend pull request #2
Opened 2017-11-15 04:31 UTC by ogusti

https://build-xpldvgjdmf.now.sh/homes

2017-11-15 21:55 UTC, evgenyrodionov commented
Зафиксируй хедер, фильтры и карту

2017-11-15 21:56 UTC, evgenyrodionov commented
Карта неправильно сделана — должна уходить в край

2017-11-15 21:56 UTC, evgenyrodionov commented
Лого не кликабельно

2017-11-15 21:56 UTC, evgenyrodionov commented
Нижний отступ у футера сожрало

![image](https://user-images.githubusercontent.com/775692/32862368-fbe6e3ae-ca68-11e7-838e-4a7650d14ad1.png)

2017-11-16 18:39 UTC, evgenyrodionov commented
Карта всё также плоха — теперь уходит вниз

для ссылок нужно использовать реакт-роутеровский Link

2017-11-16 18:44 UTC, imevro requested changes

2017-11-16 18:44 UTC, evgenyrodionov commented on src/Homes/index.js
> +                sub="161"
числа нужно передавать числами

2017-11-16 18:44 UTC, evgenyrodionov commented on src/Landing/Footer/Styled.js
> +  @media (max-width: 400px) {
говорил же max-width не использовать

2017-11-17 12:40 UTC, evgenyrodionov commented
Ссылку на деплой после запроса ревью, а не в первом комментарии

2017-11-17 12:42 UTC, evgenyrodionov commented
Чё-то не то с отступами между текстами

![image](https://user-images.githubusercontent.com/775692/32947787-d2fcbc84-cbad-11e7-9e21-3e62e7b60473.png)

Кликабельным мб
![image](https://user-images.githubusercontent.com/775692/32947795-d7f9975c-cbad-11e7-8e6d-ceec41aa711b.png)

Карточки плохи
![image](https://user-images.githubusercontent.com/775692/32947805-e3b72e88-cbad-11e7-85e0-4564e90553dd.png)

2017-11-17 12:44 UTC, imevro requested changes

2017-11-17 12:44 UTC, evgenyrodionov commented on src/Header/index.js
> +export const ReactRouterLink = styled(Link)`
лол, не проще ли наоборот? Импортить `{ Link as RLink }` и делать `const Link = styled(RLink)`

2017-11-17 12:44 UTC, evgenyrodionov commented on src/Landing/Footer/Styled.js
> +  @media (max-width: 400px) {
ну и чё блядь, я для кого замечания оставляю?

2017-11-17 12:44 UTC, evgenyrodionov commented on src/Landing/Homes/index.js
> +export const ReactRouterLink = styled(Link)`
зачем экспорт? Не понимаю

2017-11-17 12:44 UTC, evgenyrodionov commented on src/Landing/Homes/index.js
> +export const ReactRouterLink = styled(Link)`
в хедере то же самое

2017-11-18 08:09 UTC, ogusti commented
https://build-fzeowmjtpi.now.sh

2017-11-18 08:09 UTC, ogusti commented
https://build-fzeowmjtpi.now.sh

2017-11-18 10:49 UTC, evgenyrodionov commented
Футер когда-нибудь станет нормальным?

![image](https://user-images.githubusercontent.com/775692/32979498-53743bd0-cc67-11e7-9f74-4497daf6963e.png)
![image](https://user-images.githubusercontent.com/775692/32979499-5565ddfe-cc67-11e7-8a90-23414cfc382d.png)

2017-11-18 10:50 UTC, evgenyrodionov commented
Что с бордером у фильтров?
![image](https://user-images.githubusercontent.com/775692/32979502-63e50102-cc67-11e7-8822-a788d57c3caf.png)

Со шрифтами что?
![image](https://user-images.githubusercontent.com/775692/32979506-6d753728-cc67-11e7-9d3b-856f9bd6b7d0.png)
![image](https://user-images.githubusercontent.com/775692/32979507-6f039eb8-cc67-11e7-8913-eacd0e037dc5.png)

Отступы в карточках всё ещё не те
![image](https://user-images.githubusercontent.com/775692/32979511-75d0cf72-cc67-11e7-98bd-0346c80ae978.png)

Тут что с кнопками?
![image](https://user-images.githubusercontent.com/775692/32979515-7bb16280-cc67-11e7-9885-af943d4f7cea.png)

2017-11-18 10:51 UTC, evgenyrodionov commented
Это что за хуйня
![image](https://user-images.githubusercontent.com/775692/32979518-8d4fb564-cc67-11e7-9e53-e5d7f8832d0a.png)

2017-11-18 10:51 UTC, evgenyrodionov commented
И смени название репозитория наконец

2017-11-18 19:10 UTC, ogusti commented
https://build-rvwzviakrh.now.sh

2017-11-19 23:47 UTC, evgenyrodionov commented
Ну и что с бордером под фильтром?
![image](https://user-images.githubusercontent.com/775692/32997153-22a5dd88-cd9d-11e7-9d15-c88c2fea4179.png)

2017-11-19 23:48 UTC, imevro requested changes

2017-11-19 23:48 UTC, evgenyrodionov commented on src/Homes/CalendarReact.js
> +const Mobile = props => <Responsive {...props} maxWidth={767} />;
вынеси в UI

2017-11-19 23:48 UTC, evgenyrodionov commented on src/Homes/DropDown.js
> +const FilterItem = styled.button`
фильтр хуитем

2017-11-19 23:48 UTC, evgenyrodionov commented on src/Homes/DropDown.js
> +    if (this.state.isOpen) {
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Conditional_Operator

2017-11-21 08:59 UTC, ogusti commented
https://build-rgiltpgqvo.now.sh

2017-11-21 09:39 UTC, evgenyrodionov commented
ДА ЕБАНЫЙ В РОТ
СКОЛЬКО МОЖНО ПОВТОРЯТЬ

БОРДЕР
ПОД
ФИЛЬТРОМ
ДОЛЖЕН
БЫТЬ
В
КРАЙ
СТРАНИЦЫ
КАК
НА
МАКЕТЕ

https://github.com/cp3r/airbnb-frontend/pull/3

2017-11-21 09:39 UTC, evgenyrodionov commented
<img width="79" alt="screen shot 2017-11-21 at 12 40 29 pm" src="https://user-images.githubusercontent.com/775692/33065135-1243afd4-ceb9-11e7-88db-8107428f98c8.png">

2017-11-21 09:40 UTC, evgenyrodionov commented
Отступы в карточках не поменялись
<img width="396" alt="screen shot 2017-11-21 at 12 41 12 pm" src="https://user-images.githubusercontent.com/775692/33065175-2a22eef8-ceb9-11e7-80ee-6c6532d88401.png">

2017-11-21 10:16 UTC, ogusti commented
https://build-qcmvlhzwyb.now.sh

2017-11-21 13:32 UTC, imevro requested changes

2017-11-21 13:32 UTC, evgenyrodionov commented on src/Homes/Filters/DropDown.js
> +    alert("Apply");
выкинь

2017-11-21 13:32 UTC, evgenyrodionov commented on src/Homes/Filters/DropDown.js
> +  onApply = e => {
ставь отступы между методами

2017-11-21 13:32 UTC, evgenyrodionov commented on src/Homes/Filters/DropDown.js
> +      ? this.setState({ isOpen: true })
https://developer.mozilla.org/en/docs/Web/JavaScript/Reference/Operators/Conditional_Operator

2017-11-21 13:32 UTC, evgenyrodionov commented on src/Homes/Filters/Filters.js
> +import CalendarReact from "./Calendar/CalendarReact";
не понял

2017-11-21 14:23 UTC, ogusti commented
https://build-hpxkveymeh.now.sh/

2017-11-22 12:34 UTC, evgenyrodionov commented
бля по макету вообще другое дело!

2017-11-22 12:43 UTC, evgenyrodionov commented
Делаешь гит пулл в мастере, от него новый бранч. Если уже работал в каком-то другом — заберёшь коммиты через git cherry-pick.

Работать в том нельзя, потому что я сделал мердж через сквош — все коммиты схлопнулись в один и потому история будет разительно отличаться, а это приведёт к мерджконфликтам на пустом месте.

2017-11-22 12:43 UTC, merged